### ISSUE TITLE
"Convert to" option stopped working

### ISSUE THREAD

**Issue by Silver1188** [tubededentifrice/streamdeck-crypto#10]
Love your stream deck addon!

I used to be able to select Canadian $ as a conversion option under the "convert to" pulldown menu but now the menu is blank/broken and displays no options.

Just a me problem or more widespread?

**Comment by kyle604t** [comment]
Same issue for me :( 
![Crytpo](https://user-images.githubusercontent.com/82292584/114286225-b5ca7d00-9a11-11eb-884f-be2f0a24b74a.jpg)

**Comment by tubededentifrice** [comment]
Hey there
I'm aware of this issue, caused by https://exchangeratesapi.io stopping providing services without an API key.
I've a work around in progress, already commited to master but that I'm still testing. I'll probably publish the new version this week. The new version has major changes and will also support regular stocks.

Sorry for the inconvenience.
