### ISSUE TITLE
App broken!

### ISSUE THREAD

**Issue by mrksnrm** [tubededentifrice/streamdeck-crypto#11]
Hi!

Streamdeck Crypto Ticker Pro app seems to be broken, do not see most of the data(Binance) last couple of days.

**Comment by osx86x** [comment]
same here - now the tiles show up as a black square while others are unresponsive when switching tickers / updating settings

**Comment by tubededentifrice** [comment]
I had some problems with the proxy app (which allows the plugin to talk to the different data providers in the same way).
This should be resolved now.

This app is needed because some access to some data now requires a private API key that I can't embed in the plugin without being charged a ton, but I'd like to get rid of most of this proxy to avoid those kind of issues when I've time

**Comment by osx86x** [comment]
Thank you so much the update. Fantastic app and don't stop being amazing!
