### ISSUE TITLE
Alert background color

### ISSUE THREAD

**Issue by mrksnrm** [tubededentifrice/streamdeck-crypto#2]
Hi!

Thanks for the Crypto Ticker Pro, nice tool!
Didn't find any other way to leave a message, but I have one feature request. It would be nice to have option to set 2 different background colors for one widget. One user-defined color if price goes under the set limit and other user-defined color in case if price goes over the set limit.
Currently there is only one alert color and it does not give quick feedback did the price went up or down. I have set 16 different crypto currencies and it would be helpful to see in a second the overall status (is market red or green).

Regards,
Marko

**Comment by osx86x** [comment]
I would also appreciate if you could help extend this to allow changing background colour (Green/Red) based on amount/price change since yesterday (DAILY_CHANGE or DAILY_CHANGE_RELATIVE) - might be easier to implement. Looks good so far too.

**Comment by tubededentifrice** [comment]
Sorry about the long reply, Github notifications are broken (I'm not on the to: and messages are trashed)

@mrksnrm You can do it with a custom background color rule, eg. `(value<11?"yellow":(value>15?"red":"orange"))`

@osx86x that's indeed a good idea, I'll try to introduce new variables, eg. `value24h`, `change24h`, `changePercent24h`, stay tunned

**Comment by tubededentifrice** [comment]
OK I've introduced a set of new variables available for the alerts, as well as fixing the annoying "settings doesn't load" bug.
I'll send them the updated package so they can update the plugin.

Variables are:

`value` is the last price (displayed value).
`changeDaily` is the amount that the last price has changed since yesterday.
`changeDailyPercent` is the relative price change since yesterday (*100 for percentage change).
`volume` is daily volume.
`high` is the daily high.
`low` is the daily low.
