### ISSUE TITLE
Coin Updates

### ISSUE THREAD

**Issue by Omnibotzzzz** [tubededentifrice/streamdeck-crypto#7]
Hello - Any chance you can list the coins on the binance websites (regular & us) and coinbase? Or is there a way I can modify to add those? 

Thank you, I use it often!

**Comment by tubededentifrice** [comment]
Hey there
I actually just did it! https://github.com/tubededentifrice/streamdeck-crypto/commit/f4062a37aa4c7d7fa711d0ed5db2092af30ded80

I only added Binance though, because it supports so many cryptocurrencies, in addition to Bitfinex. I don't plan to support Coinbase though (I'm not even sure they have a market API).

I publish the update to the market, so you should be able to use it very soon.
